In [1]:
#predavanje




In [2]:
## 1 dio


In [3]:
12



12

In [4]:
type(12)


int

In [5]:
# int je cijeli broj


In [6]:
type(12.5)

float

In [7]:
# float, decimalni broj


In [8]:
type("Klara"
)

str

In [9]:
#str, riječ


In [10]:
"APLLE"


'APLLE'

In [11]:
True

True

In [12]:
False

False

In [13]:
3 > 5


False

In [14]:
7 < 2


False

In [17]:
#dictionaries {}
#list []
#tuple ()
# ( ) ne mijenjaju se
#list, mogu se mijenjati tijekom koda
# dic, dodajemo svakoj var jednu var, povezivanje dvije stvari, godine, ime, koji smjer


In [22]:
 t=[1,2,3]

In [20]:
type([1,2,3])

list

In [21]:
#liste se mogu imenovati

In [23]:
t

[1, 2, 3]

In [24]:
plants= {"apple": "a fruit", "banana":" a herb"}

In [26]:
type({"apple":"a fruit", "banana": "a herb"})

dict

In [27]:
plants

{'apple': 'a fruit', 'banana': ' a herb'}

In [32]:
import pandas as pd

In [31]:
plants ["banana"]

' a herb'

In [33]:
pd.DataFrame(plants, [0,1])

apple   banana
0  a fruit   a herb
1  a fruit   a herb

In [34]:
#broji se od 0, ne od 1


In [35]:
squares= [ 1,4,9,16,25]

In [37]:
type (squares)

list

In [38]:
squares

[1, 4, 9, 16, 25]

In [39]:
squares[4]

25

In [40]:
squares[-2]

16

In [42]:
#ide se sa suprotne strane, zato je 16
#: od kud, do kuda se lista printa

In [43]:
squares[:]

[1, 4, 9, 16, 25]

In [44]:
squares[1:]

[4, 9, 16, 25]

In [45]:
#od 1 nadalje

In [46]:
squares[1:3]

[4, 9]

In [47]:
#uključuje 1 i 2, 3 neće

In [48]:
squares + [36,49,64,81,100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [49]:
# dodatak u listu sa +

In [50]:
squares

[1, 4, 9, 16, 25]

In [51]:
# nije zapamtio, samo je jednom zbrojio

In [52]:
sq2= squares + [36,49,64,81,100]

In [53]:
sq2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [54]:
#za spremanje liste treba ime, i =

In [55]:
animals= ["cat", "dog", "bird"]

In [57]:
animals[0]

'cat'

In [58]:
len(sq2)

10

In [59]:
#provjera dužine liste

In [60]:
len(sq2[:5])

5

In [61]:
#od početka do 5

In [62]:
letters= ["a", "b", "c", "d", "e", "f", "g"]

In [63]:
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [66]:
#dodavanje između elementa 1 i 2

In [65]:
letters[1:2] =[1,2,3,4,5]
letters

['a', 1, 2, 3, 4, 5, 'c', 'd', 'e', 'f', 'g']

In [67]:
len(letters)

11

In [68]:
#apsolutni broj

In [69]:
abs(1)

1

In [70]:
abs(-10)

10

In [71]:
import operator

In [72]:
#već programirano, lakše nam bude onda, skraćivanje koda

In [73]:
1 + 3

4

In [74]:
#računa sam

In [76]:
operator .add(1, 3)

4

In [77]:
#npr za stat je lakse, za t test ili slično

In [78]:
operator.sub(1,10)

-9

In [79]:
operator.eq(1,10)

False

In [80]:
#nisu jednaki

In [83]:
#print

In [84]:
print(1)

1


In [85]:
#ispiše to što je u zagradi

In [92]:
print("this" + "" + "is" +"a"+ "full"+"sentance"  )

thisisafullsentance


In [88]:
#treba biti razmak


In [89]:
print("this", "is", "a", "full", "sentance")

this is a full sentance


In [90]:
#ako su zarezi onda ne moramo stavljati razmak, sam skuži

In [91]:
print(sq2[1:5])

[4, 9, 16, 25]


In [93]:
None

In [94]:
# sam je kuži, kao i is i is not

In [95]:
type(None)

NoneType

In [96]:
#nema tipa

In [104]:
##funkcije, operacija koju radi za nas, mi ju definiramo, damo ime, mat operacija, i return result

In [105]:
def our_function(x) :
  """This function multiplies its argumen by 2
  written by Klara"""
  result = x*2
  return result


In [106]:
our_function(5)

10

In [108]:
our_function(3.14)

6.28

In [109]:
type(our_function)

function

In [110]:
import math

In [111]:
def ph(c):
  """This function calculates th pH of a solution.
  it uses the concetracion of the H+ in mol/L.
  it returns the pH."""
  ph_value = -math.log10(c)
  return ph_value

In [112]:
ph(0.001)

3.0

In [113]:
def ph1(c):
  return -math.log10(c)

In [114]:
ph1(0.001)

3.0

In [115]:
#isto je i bez return, isto napiše rezultat, ovako je za kraće funkcije

In [116]:
def task(x,y):
  """definicija"""
  print("this is the log10 of x", math.log10(x))
  print("this is the log10 of y", math.log10(y))
  new_number= math.log10(x)+ math.log(y)
  print("the result is below:")
  return new_number

In [117]:
task(1000,2.73)

this is the log10 of x 3.0
this is the log10 of y 0.436162647040756
the result is below:


4.004301609196869

In [118]:
def konv_eur(euro):
  dkk= euro*7.55
  return dkk

In [119]:
#ne zna što je euro, ali smo ga def kao broj, bitno je da budemo doslijedni u tome, nije mu bitno ime, to je više za nas

In [120]:
konv_eur(10)

75.5

In [121]:
def plus(a,b,c,d):
  suma= a + b + c + d
  return suma

In [122]:
plus(3,4,5,6)

18

In [125]:
# = i ==

In [126]:
1 == 1

True

In [127]:
# u pravom mat smislu je točno, = je ime

In [128]:
k= (1,2,3)

In [129]:
k

(1, 2, 3)

In [130]:
type(k)

tuple

In [131]:
width = 20
height = 5*90
height, width

(450, 20)

In [135]:
width == 30

True

In [136]:
width == 20

False

In [134]:
width = 30

In [137]:
cp1 = 'Tomo'
cp2= ' Maria'
cp1, cp2

('Tomo', ' Maria')

In [138]:
width == height

False

In [139]:
width = height

In [140]:
width == height

True

In [141]:
width

450

In [142]:
cp1 == cp2

False

In [143]:
cp1 != cp2

True

In [144]:
# != za nije jednako, dok je == za jednako

In [145]:
# is i is not

In [146]:
5 is 4

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-171648558.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 4


False

In [147]:
5 is 5

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-1783323536.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 5


True

In [148]:
width is height

True

In [149]:
#ranije definirano da je tako


In [150]:
width is not height

False

In [151]:
#liste

In [152]:
squares

[1, 4, 9, 16, 25]

In [153]:
squares.append(36)

In [154]:
squares

[1, 4, 9, 16, 25, 36]

In [155]:
#dodali smo 36 u listu

In [156]:
squares_part2= squares + [36]

In [157]:
squares

[1, 4, 9, 16, 25, 36]

In [158]:
squares_part2

[1, 4, 9, 16, 25, 36, 36]

In [159]:
last_list =squares.copy()

In [160]:
last_list

[1, 4, 9, 16, 25, 36]

In [161]:
squares.append(10)

In [162]:
last_list

[1, 4, 9, 16, 25, 36]

In [163]:
squares

[1, 4, 9, 16, 25, 36, 10]

In [164]:
#append se uvijek doda na kraj, osim ako mi to sami ne napišemo

In [168]:
print('Participants in the course were' , cp1 , 'and', cp2 ,'.' )

Participants in the course were Tomo and  Maria .


In [167]:
# sve mora biti odvojeno zarezima

In [171]:
print('Participants in the course were %s and %s'
  %(cp1, cp2))

Participants in the course were Tomo and  Maria


In [172]:
sample = 'u552'

In [173]:
conc= 0.002
print('In a sample %s we found %s mg/L of drugs' %(sample, conc))

In a sample u552 we found 0.002 mg/L of drugs


In [174]:
print (f'In a sample {sample} we found {conc} mg/L of drugs')

In a sample u552 we found 0.002 mg/L of drugs


In [175]:
def bmi(w,h) :
  bmi = w/h**2
  return bmi

In [176]:
#**2 na kvadrat

In [178]:
bmi(w=60, h=1.69)

21.007667798746546

In [179]:
bmi(60, 1.69)

21.007667798746546

In [180]:
#može jedno i drugo, svejedno je

In [183]:
 #c1 * v1 = c2 * v2

In [191]:
def diluter(c1=0.5 ,v1=1, v2=2):
  '''Calculating dilutions
  returns c2'''
  c2 = c1*v1/v2
  return c2

In [192]:
diluter(0.5,1,2)

0.25

In [193]:
help(diluter)

Help on function diluter in module __main__:

diluter(c1=0.5, v1=1, v2=2)
    Calculating dilutions
    returns c2



In [194]:
#piše nam o našoj funkciji

In [195]:
diluter(2)

1.0

In [196]:
diluter(2,1,3)

0.6666666666666666

In [197]:
def factor_corrections(c, f=1):
  conc=c*f
  return conc

In [198]:
factor_corrections(0.0002, 0.01)

2.0000000000000003e-06

In [199]:
factor_corrections(0.0002)

0.0002

In [200]:
def do_something_else(a=1, b=2, c=3):
  return(a,b,c,)

In [202]:
do_something_else()

(1, 2, 3)

In [203]:
do_something_else(10,10)

(10, 10, 3)

In [204]:
do_something_else(10,10)

(10, 10, 3)

In [205]:
do_something_else(5,5,c=5)

(5, 5, 5)

In [206]:
#isto je i ako stavimo c=5 ili samo 5 na njegovo mjesto

In [207]:
do_something_else(a=10)

(10, 2, 3)

In [208]:
def suma(a,b,):
  return a+b

def adding_3rd(a,b,c,):
  return suma (a,b)+ c

adding_3rd(1,2,3)

6

In [209]:
#možemo pozivati i funkcije u funkcije

In [210]:
#for

In [218]:
my_friends= ['Ivan', 'Tomo', 'Maria', 'Petar ']

In [214]:
my_friends

['Ivan', 'Tomo', 'Maria', 'Petar ']

In [219]:
for x in my_friends:
  print (x)

Ivan
Tomo
Maria
Petar 


In [222]:
def bmi(w,h):

  bmi= w/h**2
  return bmi

In [223]:
weights=[80,55,60,40]
heights= [1.60, 1.55, 1.70, 1.80]

for x, friend in enumerate(my_friends):
  bmi_person = bmi(weights[x], heights[x])
  print(f'{friend} had bmi of {bmi_person}')

Ivan had bmi of 31.249999999999993
Tomo had bmi of 22.892819979188342
Maria had bmi of 20.761245674740486
Petar  had bmi of 12.345679012345679


In [224]:
print(f'{friend} has bmi of {bmi_person}')

Petar  has bmi of 12.345679012345679


In [225]:
#piše nam samo zadnji, to mu ostaje u memoriji

In [226]:
bmi_person

12.345679012345679

In [227]:
squares

[1, 4, 9, 16, 25, 36, 10]

In [228]:
squares= [1,4,9,16,25]

In [229]:
squares

[1, 4, 9, 16, 25]

In [230]:
for x in squares:
  print('Element is %s' %x)

Element is 1
Element is 4
Element is 9
Element is 16
Element is 25


In [231]:
for number in squares:
  print(number)

1
4
9
16
25


In [232]:
course_part =[cp1, cp2]

In [233]:
course_part

['Tomo', ' Maria']

In [234]:
for name in course_part:
  print(name)

Tomo
 Maria


In [235]:
for pos in range(len(course_part)):
  print(pos)

0
1


In [236]:
#pos- pozicija, len-dužina

In [237]:
for number, element in enumerate(squares):
  print(number, element)

0 1
1 4
2 9
3 16
4 25


In [238]:
squares

[1, 4, 9, 16, 25]

In [239]:
import math

In [240]:
for number in squares:
  sq_root= math.sqrt(number)
  print(sq_root)

1.0
2.0
3.0
4.0
5.0


if else =
==
<
<=
>
=>

In [241]:
1 <=2

True

In [242]:
# <= manje ili jednako

In [244]:
if 1 == 1:
  print('yes')
  print('da')
  print('oui')

yes
da
oui


In [245]:
1 ==2

False

In [246]:
cp1= 'Mila'
cp2= 'Marko'

In [247]:
if cp1== cp2:
  print('da')

In [248]:
if cp1 !=cp2:
  print('da')

da


In [249]:
if cp1 == cp2:
  print('da')

else:
  print('ne')

ne


In [251]:
#else mora biti u razini if, inače neće biti dobro

In [260]:
def check_gender_by_name(name):
  if name[-1]=='a':
    gender = 'female'
  elif name[-1]== 'o':
    gender= 'male'
  else:
    gender='unknown'

  return gender

In [261]:
check_gender_by_name('Mila')

'female'

In [262]:
check_gender_by_name('Marko')

'male'

In [265]:
def ph(c):
  return -math.log10(c)


In [266]:
ph(0.001)

3.0

In [269]:
def ph_evaluator(c=0.001):
  'Ph decision maker'
  ph_value= ph(c)

  if ph_value < 7:
    decision='kiselo'
  else:
    decision= 'lužnato'


  return decision
ph_evaluator()

'kiselo'

In [283]:
def ph_evaluator(c=0.001):

  if ph(c) < 7:
    return 'kiselo'

  else:
    return 'lužnato'
conc_list= [0.001, 0.01, 0.1, 1, 10]
for solution in conc_list:
  print(ph_evaluator(solution))

kiselo
kiselo
kiselo
kiselo
kiselo


In [274]:
def test_if_else(a,b):

  '''a,b su argumenti
  return 'a > b' of 'a in not > b'
  '''
  if a > b:
    print(a,'>', b)

  else:
    print('%d is not > %d' %(a,b))

In [279]:
test_if_else(6,2)

6 > 2


In [280]:
test_if_else(2,6)

2 is not > 6


In [284]:
help(test_if_else)

Help on function test_if_else in module __main__:

test_if_else(a, b)
    a,b su argumenti
    return 'a > b' of 'a in not > b'



In [285]:
def rectangle_area(a,b):
  '''dokumentacija'''

  A=a*b
  if a == b:
    print('kvadrat')
  else:
    print('pravokutnik')
  return A

In [286]:
rectangle_area(2,3)

pravokutnik


6

In [287]:
rectangle_area

<function __main__.rectangle_area(a, b)>

In [289]:
for letter in [1,2,3]:
  print('broj:' , letter)

broj: 1
broj: 2
broj: 3


In [290]:
x = 5

In [291]:
x

5

In [292]:
x = 7

In [293]:
x


7

In [294]:
#pamti ono zadnje, ne ono prije

In [295]:
y =2

In [296]:
x +y

9

In [297]:
površina= rectangle_area(5,4)

pravokutnik


In [298]:
površina

20

In [299]:
(-3)**4

81

In [300]:
-(3**4)

-81

In [301]:
3 * 3.75 / 1.5

7.5

In [302]:
a = [4,5,6]
n = [1,2,3]

In [303]:
x = [a,n]

In [304]:
x

[[4, 5, 6], [1, 2, 3]]

In [306]:
#dobijemo matricu jednostavnu, ne spaja u jednu listu

In [307]:
import numpy as np

In [308]:
nums1 = [1,2,3,4,5]
nums1

[1, 2, 3, 4, 5]

In [309]:
nums2 = np.array(nums1)

In [310]:
type(nums2)

numpy.ndarray

In [311]:
nums2

array([1, 2, 3, 4, 5])

In [312]:
type(nums1)

list

In [313]:
#array može imati drugačije objekte, 1,2,3 ili 12, a,b, 45 i možemo raditi sa time, ako dodamo a prebacuje ga u string

In [314]:
max(nums1)

5

In [316]:
min(nums1)

1

In [317]:
np.min(nums1)

np.int64(1)

In [318]:
#numpy dodaje 64 inače, ne znamo što znači..


In [319]:
x1= np.array([1.3, 0, 2])
x1

array([1.3, 0. , 2. ])

In [324]:
x2= np.array([1, 0, 2])

In [325]:
x2

array([1, 0, 2])

In [328]:
type(x1), type(x2)

(numpy.ndarray, numpy.ndarray)

In [329]:
x1.dtype, x2.dtype

(dtype('float64'), dtype('int64'))

In [330]:
#float- decimalni, int- cijeli


In [331]:
x2= np.arange(20,50,2)
x2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [334]:
# 20- od koliko ide, uključen je
#50- do koliko ide, nije uključen
#2- po 2 ide, koliki je korak

In [338]:
np.linspace(10,20,10, endpoint=True)


array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [339]:
np.linspace(10,20,10, endpoint=False)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [340]:
nule= np.zeros((5,3))
nule.shape

(5, 3)

In [341]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [343]:
x4 = np.random.random((3,10))

In [344]:
x4

array([[0.57231867, 0.84278125, 0.68867655, 0.9982646 , 0.03652341,
        0.97962431, 0.80405636, 0.43099507, 0.03149061, 0.6854567 ],
       [0.70149012, 0.74690256, 0.77124488, 0.77144545, 0.18036173,
        0.5759356 , 0.91669784, 0.08126124, 0.93766023, 0.56504577],
       [0.90186525, 0.9977933 , 0.30170503, 0.11406286, 0.39988588,
        0.56455755, 0.48629761, 0.28023528, 0.38026082, 0.22039407]])

In [345]:
import pandas as pd


In [346]:
pd.DataFrame(x4)

0         1         2         3         4         5         6  \
0  0.572319  0.842781  0.688677  0.998265  0.036523  0.979624  0.804056   
1  0.701490  0.746903  0.771245  0.771445  0.180362  0.575936  0.916698   
2  0.901865  0.997793  0.301705  0.114063  0.399886  0.564558  0.486298   

          7         8         9  
0  0.430995  0.031491  0.685457  
1  0.081261  0.937660  0.565046  
2  0.280235  0.380261  0.220394

In [347]:
x4.dtype

dtype('float64')

In [348]:
x4.shape

(3, 10)

In [349]:
x4.reshape(10,3)

array([[0.57231867, 0.84278125, 0.68867655],
       [0.9982646 , 0.03652341, 0.97962431],
       [0.80405636, 0.43099507, 0.03149061],
       [0.6854567 , 0.70149012, 0.74690256],
       [0.77124488, 0.77144545, 0.18036173],
       [0.5759356 , 0.91669784, 0.08126124],
       [0.93766023, 0.56504577, 0.90186525],
       [0.9977933 , 0.30170503, 0.11406286],
       [0.39988588, 0.56455755, 0.48629761],
       [0.28023528, 0.38026082, 0.22039407]])

In [350]:
x4.T

array([[0.57231867, 0.70149012, 0.90186525],
       [0.84278125, 0.74690256, 0.9977933 ],
       [0.68867655, 0.77124488, 0.30170503],
       [0.9982646 , 0.77144545, 0.11406286],
       [0.03652341, 0.18036173, 0.39988588],
       [0.97962431, 0.5759356 , 0.56455755],
       [0.80405636, 0.91669784, 0.48629761],
       [0.43099507, 0.08126124, 0.28023528],
       [0.03149061, 0.93766023, 0.38026082],
       [0.6854567 , 0.56504577, 0.22039407]])

In [351]:
np.arange(2,20). reshape(2,3,3).T

array([[[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]],

       [[ 4, 13],
        [ 7, 16],
        [10, 19]]])

In [352]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [353]:
I = np.eye(40)
I

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [354]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [356]:
A @ A

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [357]:
# @ za množenje matrica